### ISSUE TITLE
Event handlers are lost when displaying popup

### ISSUE THREAD

**Issue by aztechowski** [fidley/falv#41]
I have following scenario. Main FALV grid with button that is creating popup with another FALV. On that popup there is button 'SAVE' allowing to save data from popup into DB. I've registered event handler to handle aforementioned SAVE button as follow:
`SET HANDLER me->on_user_command FOR me->mo_license_list->mo_falv.`
As you can see event handler is outside FALV. 
The issue is that FALV, when is displaying popup, is copying his instance but then all such registered event handlers are lost.  Only those implemented as FALV methods are kept.
The only way to overcome that limitation is to register event as follow:
`SET HANDLER me->on_user_command FOR ALL INSTANCES.`
Maybe there is better way to do it?

**Comment by fidley** [comment]
There is one problem with popups, I have to create a copy of instance because grid created not in PBO is then not displayed on the screen. As far as I know there is no possiblity to copy handlers, in case of FALV I just set it up again for new instance.

![image](https://user-images.githubusercontent.com/7912195/28416759-9ebf0f28-6d55-11e7-8c3d-94092cb4a56b.png)

This can be seen as limitation of FALV. Of course all your methods implemented handlers inside FALV should work as you also mentioned. Your way of overcoming seems the only way. I was trying to find a way to do it as well -> https://archive.sap.com/discussions/thread/3841643 , but I was so far unsuccesful.

**Comment by fidley** [comment]
Should be solved with the solution to #58
